# Hardcoded list of major companies and their tickers for fuzzy matching

COMPANY_TICKER_MAP = {
    # Tech Giants
    "apple": "AAPL",
    "microsoft": "MSFT",
    "alphabet": "GOOGL",
    "google": "GOOGL",
    "amazon": "AMZN",
    "meta": "META",
    "facebook": "META",
    "nvidia": "NVDA",
    "tesla": "TSLA",
    "netflix": "NFLX",
    "adobe": "ADBE",
    "salesforce": "CRM",
    "oracle": "ORCL",
    "intel": "INTC",
    "amd": "AMD",
    "ibm": "IBM",
    "cisco": "CSCO",
    "qualcomm": "QCOM",
    "broadcom": "AVGO",
    "texas instruments": "TXN",
    "asml": "ASML",
    "servicenow": "NOW",
    "snowflake": "SNOW",
    "paypal": "PYPL",
    "square": "SQ",
    "block": "SQ",
    "uber": "UBER",
    "lyft": "LYFT",
    "airbnb": "ABNB",
    "spotify": "SPOT",
    "zoom": "ZM",
    "slack": "CRM",
    "shopify": "SHOP",
    "twilio": "TWLO",
    "okta": "OKTA",
    "datadog": "DDOG",
    "crowdstrike": "CRWD",
    "palantir": "PLTR",
    "roblox": "RBLX",
    "unity": "U",
    "coinbase": "COIN",
    
    # Financial Services
    "jpmorgan": "JPM",
    "bank of america": "BAC",
    "wells fargo": "WFC",
    "citigroup": "C",
    "goldman sachs": "GS",
    "morgan stanley": "MS",
    "american express": "AXP",
    "visa": "V",
    "mastercard": "MA",
    "berkshire hathaway": "BRK-B",
    "charles schwab": "SCHW",
    "blackrock": "BLK",
    "s&p global": "SPGI",
    "capital one": "COF",
    "us bancorp": "USB",
    "pnc": "PNC",
    "truist": "TFC",
    "travelers": "TRV",
    "progressive": "PGR",
    "allstate": "ALL",
    "metlife": "MET",
    "prudential": "PRU",
    "aig": "AIG",
    "chubb": "CB",
    "marsh mclennan": "MMC",
    "aon": "AON",
    
    # Healthcare & Pharma
    "unitedhealth": "UNH",
    "johnson & johnson": "JNJ",
    "pfizer": "PFE",
    "abbvie": "ABBV",
    "eli lilly": "LLY",
    "merck": "MRK",
    "bristol myers": "BMY",
    "abbott": "ABT",
    "thermo fisher": "TMO",
    "danaher": "DHR",
    "medtronic": "MDT",
    "amgen": "AMGN",
    "gilead": "GILD",
    "regeneron": "REGN",
    "moderna": "MRNA",
    "vertex": "VRTX",
    "biogen": "BIIB",
    "illumina": "ILMN",
    "intuitive surgical": "ISRG",
    "stryker": "SYK",
    "boston scientific": "BSX",
    "zimmer biomet": "ZBH",
    "edwards lifesciences": "EW",
    "agilent": "A",
    "waters": "WAT",
    "iqvia": "IQV",
    "humana": "HUM",
    "cigna": "CI",
    "elevance": "ELV",
    "centene": "CNC",
    "cvs": "CVS",
    "walgreens": "WBA",
    "mckesson": "MCK",
    "cardinal health": "CAH",
    "amerisourcebergen": "ABC",
    
    # Consumer & Retail
    "walmart": "WMT",
    "home depot": "HD",
    "mcdonalds": "MCD",
    "nike": "NKE",
    "starbucks": "SBUX",
    "coca cola": "KO",
    "pepsi": "PEP",
    "procter gamble": "PG",
    "costco": "COST",
    "target": "TGT",
    "lowes": "LOW",
    "tjx": "TJX",
    "booking": "BKNG",
    "marriott": "MAR",
    "hilton": "HLT",
    "chipotle": "CMG",
    "yum brands": "YUM",
    "dominos": "DPZ",
    "wendys": "WEN",
    "dunkin": "DNKN",
    "panera": "PNRA",
    "colgate": "CL",
    "kimberly clark": "KMB",
    "general mills": "GIS",
    "kellogg": "K",
    "kraft heinz": "KHC",
    "mondelez": "MDLZ",
    "hershey": "HSY",
    "campbell": "CPB",
    "tyson foods": "TSN",
    "hormel": "HRL",
    "conagra": "CAG",
    "estee lauder": "EL",
    "ulta": "ULTA",
    "ralph lauren": "RL",
    "gap": "GPS",
    "lululemon": "LULU",
    "under armour": "UAA",
    "vf corp": "VFC",
    "hanesbrands": "HBI",
    "pvh": "PVH",
    "tapestry": "TPR",
    "capri": "CPRI",
    
    # Industrial & Manufacturing
    "boeing": "BA",
    "caterpillar": "CAT",
    "3m": "MMM",
    "honeywell": "HON",
    "ge": "GE",
    "general electric": "GE",
    "lockheed martin": "LMT",
    "raytheon": "RTX",
    "northrop grumman": "NOC",
    "general dynamics": "GD",
    "united technologies": "RTX",
    "deere": "DE",
    "john deere": "DE",
    "paccar": "PCAR",
    "cummins": "CMI",
    "emerson": "EMR",
    "eaton": "ETN",
    "parker hannifin": "PH",
    "rockwell": "ROK",
    "dover": "DOV",
    "ingersoll rand": "IR",
    "stanley black": "SWK",
    "fortive": "FTV",
    "illinois tool": "ITW",
    "roper": "ROP",
    "xylem": "XYL",
    "pentair": "PNR",
    "idex": "IEX",
    "graco": "GGG",
    
    # Energy
    "exxon": "XOM",
    "chevron": "CVX",
    "conocophillips": "COP",
    "schlumberger": "SLB",
    "marathon": "MPC",
    "valero": "VLO",
    "phillips 66": "PSX",
    "occidental": "OXY",
    "pioneer": "PXD",
    "eog": "EOG",
    "devon": "DVN",
    "halliburton": "HAL",
    "baker hughes": "BKR",
    "kinder morgan": "KMI",
    "williams": "WMB",
    "oneok": "OKE",
    "enbridge": "ENB",
    "cheniere": "LNG",
    "nextera": "NEE",
    "duke energy": "DUK",
    "southern company": "SO",
    "dominion": "D",
    "american electric": "AEP",
    "exelon": "EXC",
    "xcel": "XEL",
    "constellation": "CEG",
    
    # Telecom & Media
    "disney": "DIS",
    "comcast": "CMCSA",
    "verizon": "VZ",
    "att": "T",
    "t mobile": "TMUS",
    "charter": "CHTR",
    "warner bros": "WBD",
    "paramount": "PARA",
    "fox": "FOX",
    "live nation": "LYV",
    "electronic arts": "EA",
    "activision": "ATVI",
    "take two": "TTWO",
    "zynga": "ZNGA",
    
    # Materials & Chemicals
    "dow": "DOW",
    "dupont": "DD",
    "linde": "LIN",
    "air products": "APD",
    "ecolab": "ECL",
    "sherwin williams": "SHW",
    "ppg": "PPG",
    "newmont": "NEM",
    "freeport": "FCX",
    "nucor": "NUE",
    "steel dynamics": "STLD",
    "alcoa": "AA",
    "mosaic": "MOS",
    "cf industries": "CF",
    "corteva": "CTVA",
    "fmc": "FMC",
    "albemarle": "ALB",
    "celanese": "CE",
    "eastman": "EMN",
    "westrock": "WRK",
    "international paper": "IP",
    "ball": "BALL",
    "amcor": "AMCR",
    "sealed air": "SEE",
    "avery dennison": "AVY",
    
    # Transportation & Logistics
    "fedex": "FDX",
    "ups": "UPS",
    "union pacific": "UNP",
    "csx": "CSX",
    "norfolk southern": "NSC",
    "jb hunt": "JBHT",
    "old dominion": "ODFL",
    "delta": "DAL",
    "united airlines": "UAL",
    "american airlines": "AAL",
    "southwest": "LUV",
    "jetblue": "JBLU",
    "alaska air": "ALK",
    "spirit airlines": "SAVE",
    "carnival": "CCL",
    "royal caribbean": "RCL",
    "norwegian cruise": "NCLH",
    
    # Real Estate
    "prologis": "PLD",
    "american tower": "AMT",
    "crown castle": "CCI",
    "equinix": "EQIX",
    "public storage": "PSA",
    "realty income": "O",
    "simon property": "SPG",
    "welltower": "WELL",
    "ventas": "VTR",
    "avalonbay": "AVB",
    "equity residential": "EQR",
    "mid america": "MAA",
    "essex": "ESS",
    "invitation homes": "INVH",
    "american homes": "AMH",
    "extra space": "EXR",
    "cubesmart": "CUBE",
    "host hotels": "HST",
    "park hotels": "PK",
    "ryman": "RHP"
}

